version: '3.7'

services:
  db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - backend

  nginx:
    image: nginx:1.19.0
    volumes:
      - ./nginx/planner.conf:/etc/nginx/includes/planner.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - FASTCGI_HOST=fpm
      - FASTCGI_PORT=9000
    networks:
      - backend

  fpm:
    build: ./fpm
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1 remote_autostart=1 remote_port=9008 idekey=PHPSTORM remote_connect_back=0"
    volumes:
      - ../planner/:/code
      - ./fpm/php.ini:/usr/local/etc/php/php.ini
      - ./fpm/php-fpm.conf:/etc/php7/php-fpm.conf
    working_dir: /code
    networks:
      - backend

  planner-client:
    image: node:14.5.0
    volumes:
      - ../planner-client:/code
    working_dir: /code
    command: "npm run start:docker"
    ports:
      - "4200:4200"
    networks:
      - backend

networks:
  backend:
